// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "LocaleLayout": {
    "title": "נוף הגליל",
    "description": "אתר נוף הגליל"
  },
  "LocaleSwitcher": {
    "label": "שינוי שפה",
    "locale": "{locale, select, he {עברית} en {English} other {Unknown}}"
  },
  "HomePage": {
    "title": "כדי להתחיל, ערכו את קובץ page.tsx",
    "intro": "מחפשים נקודת התחלה או הוראות נוספות? עברו ל-<templates>תבניות</templates> או ל-<learning>מרכז הלמידה</learning>.",
    "deployNow": "פריסה עכשיו",
    "documentation": "תיעוד"
  }
};
export default messages;