// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "LocaleLayout": {
    "title": "נוף הגליל",
    "description": "אתר נוף הגליל"
  },
  "AppShell": {
    "defaultTitle": "נוף הגליל",
    "openMenu": "פתיחת תפריט",
    "navHome": "דף הבית"
  },
  "LocaleSwitcher": {
    "label": "שינוי שפה",
    "locale": "{locale, select, he {עברית} en {English} other {Unknown}}"
  },
  "HomePage": {
    "title": "ברוכים הבאים לנוף הגליל",
    "description": "מערכת ה-shell מאפשרת לכל דף ורכיב לשלוט בתפריט, בכותרת ובהודעות דרך hooks.",
    "toggleDrawer": "פתיחת/סגירת תפריט",
    "showSnackbar": "הצגת הודעה",
    "drawerOpened": "התפריט נפתח",
    "demoSnackbar": "הודעה מהדף"
  }
};
export default messages;
